name: BalloonsPlus
main: be.shark_zekrom.Main
version: 1.6.1
api-version: 1.13
description: Create a balloon
commands:
  balloons+:
    aliases:
      - ballons
      - balloons
    description: balloons